// Package markdown renders a domain model as a Markdown document with an
// embedded Mermaid relationships diagram. The output is meant to be committed
// next to the YAML source and read directly by people and agents.
package markdown

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"

	"github.com/stacklok/modelith/internal/model"
	"github.com/stacklok/modelith/internal/render/mermaid"
)

// MDX comment syntax ({/* */}) rather than an HTML comment (<!-- -->): the docs
// are consumed by Docusaurus v3, whose MDX parser rejects HTML comments.
const generatedBanner = "{/* Generated by `modelith render`. Do not edit by hand; edit the .modelith.yaml source and re-render. */}"

var (
	// qualifiedTypeRE matches an attribute type that references an imported item,
	// "scope.Name". It mirrors the linter's pattern; the renderer only decides
	// whether to link, never whether the reference resolves.
	qualifiedTypeRE = regexp.MustCompile(`^(` + model.ScopeSlug + `)\.([A-Z][A-Za-z0-9]*)$`)
	// backtickRunRE finds the backtick runs a code span's fence has to clear.
	backtickRunRE = regexp.MustCompile("`+")
	// entityRefRE matches, anchored at an "&", the character references a
	// Markdown parser decodes. Anything else beginning with "&" is an ordinary
	// ampersand and is left alone; see escapeProse.
	entityRefRE = regexp.MustCompile(`^&(#[0-9]+|#[xX][0-9a-fA-F]+|[A-Za-z][A-Za-z0-9]*);`)
)

// Render produces the full Markdown document for the model. sourceDir is the
// directory holding the model's own .yaml (imports are written relative to
// it); outDir is the directory this Markdown is being written to (or
// sourceDir itself, for a caller with no output file — e.g. `--stdout`). Both
// must be absolute, or both relative to the same base, so the import links
// built from them are well-defined; see importLinkTarget.
func Render(m *model.Model, sourceDir, outDir string) string {
	var b strings.Builder

	b.WriteString(generatedBanner)
	b.WriteString("\n\n")

	title := m.Title
	if title == "" {
		title = "Domain Model"
	}
	fmt.Fprintf(&b, "# %s\n\n", proseLine(title))

	if desc := strings.TrimSpace(m.Description); desc != "" {
		b.WriteString(proseBlock(desc))
		b.WriteString("\n\n")
	}

	renderImports(&b, m, sourceDir, outDir)
	renderGlossary(&b, m)
	renderEnums(&b, m)
	renderEntities(&b, m, sourceDir, outDir)
	renderDiagram(&b, m)
	renderInvariants(&b, m)
	renderScenarios(&b, m)

	return b.String()
}

// renderInvariants emits the model-level invariants — cross-entity rules with no
// single owner — in a top-level section, after the relationship diagram and
// before the scenarios that exercise them. Per-entity invariants render inline
// with their entity (see renderEntities).
func renderInvariants(b *strings.Builder, m *model.Model) {
	if len(m.Invariants) == 0 {
		return
	}
	b.WriteString("## Invariants\n\n")
	for _, inv := range m.Invariants {
		fmt.Fprintf(b, "- **%s** — %s\n", inv.ID, proseLine(inv.Statement))
	}
	b.WriteString("\n")
}

// renderImports names the models this one references and where they live,
// linking each to its rendered Markdown. It never opens them: the imported
// definitions are not restated here, only pointed at, so this document stays a
// pure function of its own source (ADR-0010).
//
// The source path is shown as text and the link is labelled for what it leads
// to, because they are two different files. Labelling the link with the ".yaml"
// path while pointing it at the ".md" told the reader they were clicking
// through to the model source.
func renderImports(b *strings.Builder, m *model.Model, sourceDir, outDir string) {
	if len(m.Imports) == 0 {
		return
	}
	b.WriteString("## Imports\n\n")
	b.WriteString("Items defined in these models are referenced below as `scope.Name`.\n\n")
	// A path — and the scope a bare import derives from it — is author-supplied
	// text that reaches a published page, so both go through the same escaping
	// as every other string here, and the link destination through its own. The
	// link's own label is a fixed word, so it carries nothing to escape.
	for _, imp := range m.Imports {
		fmt.Fprintf(b, "- **%s** — %s ([rendered](%s))\n",
			codeSpan(imp.Scope), codeSpan(imp.Path), linkTarget(importLinkTarget(imp.Path, sourceDir, outDir)))
	}
	b.WriteString("\n")
}

// importAnchors maps each bound scope to the rendered Markdown of the model it
// names, for linking a qualified type. The first binding of a scope wins; a
// second one is a lint error, and the renderer stays deterministic either way.
func importAnchors(m *model.Model, sourceDir, outDir string) map[string]string {
	if len(m.Imports) == 0 {
		return nil
	}
	out := make(map[string]string, len(m.Imports))
	for _, imp := range m.Imports {
		if _, seen := out[imp.Scope]; !seen {
			out[imp.Scope] = importLinkTarget(imp.Path, sourceDir, outDir)
		}
	}
	return out
}

// importLinkTarget is the Markdown link destination for an import: the
// imported model's *default* rendered path — model.RenderedPath(impPath)
// resolved against sourceDir, i.e. where `modelith render` puts that model's
// Markdown when it is rendered in place, the documented convention — expressed
// relative to outDir. The renderer has no way to know if the imported model
// was actually rendered anywhere else, so a link only resolves when it was
// rendered at that default location.
//
// When outDir and sourceDir are the same directory (the common case: no -o,
// or --stdout, both render beside the source), impPath's own rendered form is
// already correctly relative to outDir, so it is returned unchanged rather
// than round-tripped through Join/Rel, which would needlessly normalize away
// a leading "./".
//
// An absolute impPath is a lint error (imports must be relative), but render
// only runs structural validation, so one can still reach here. Joining it
// against sourceDir would silently re-root it as if it were relative,
// producing a different, misleading link under -o than the one produced with
// no -o. Returning it unchanged keeps both cases consistent with each other
// and matches what the model actually declared.
func importLinkTarget(impPath, sourceDir, outDir string) string {
	rendered := model.RenderedPath(impPath)
	if outDir == sourceDir || filepath.IsAbs(rendered) {
		return rendered
	}
	abs := filepath.Join(sourceDir, filepath.FromSlash(rendered))
	rel, err := filepath.Rel(outDir, abs)
	if err != nil {
		// sourceDir and outDir aren't comparable (e.g. different Windows
		// volumes) — the pre-relativized path is no more wrong than any
		// alternative, and it's better than an empty link.
		return rendered
	}
	return filepath.ToSlash(rel)
}

// typeCell renders an attribute type for a table cell, linking a "scope.Name"
// reference into the imported model's Markdown. Headings render as "### `Name`",
// so the anchor is the item's name lowercased. A scope no import binds — a lint
// error — renders as written rather than as a link to nowhere.
//
// Each part is escaped for the position it lands in, before the link is
// assembled. Escaping the finished link instead would treat a URL as cell text
// and corrupt the destination.
func typeCell(typ string, targets map[string]string) string {
	match := qualifiedTypeRE.FindStringSubmatch(typ)
	if match == nil {
		return mdCell(typ)
	}
	target, ok := targets[match[1]]
	if !ok {
		return mdCell(typ)
	}
	// typ matched qualifiedTypeRE, so the label holds nothing a cell or a link
	// label reacts to.
	return fmt.Sprintf("[%s](%s#%s)", typ, linkTarget(target), strings.ToLower(match[2]))
}

func renderGlossary(b *strings.Builder, m *model.Model) {
	if len(m.Glossary) == 0 {
		return
	}
	b.WriteString("## Glossary\n\n")
	terms := make([]string, 0, len(m.Glossary))
	for t := range m.Glossary {
		terms = append(terms, t)
	}
	sort.Strings(terms)
	for _, t := range terms {
		fmt.Fprintf(b, "- **`%s`** — %s\n", t, proseLine(m.Glossary[t]))
	}
	b.WriteString("\n")
}

func renderEnums(b *strings.Builder, m *model.Model) {
	if len(m.Enums) == 0 {
		return
	}
	names := make([]string, 0, len(m.Enums))
	for n := range m.Enums {
		names = append(names, n)
	}
	sort.Strings(names)

	b.WriteString("## Enums\n\n")
	for _, name := range names {
		en := m.Enums[name]
		fmt.Fprintf(b, "### `%s`\n\n", name)
		if d := strings.TrimSpace(en.Description); d != "" {
			b.WriteString(proseBlock(d))
			b.WriteString("\n\n")
		}
		b.WriteString("| Value | Definition |\n")
		b.WriteString("| --- | --- |\n")
		for _, v := range en.Values {
			fmt.Fprintf(b, "| %s | %s |\n", codeCell(v.Name), mdCell(v.Definition))
		}
		b.WriteString("\n")
	}
}

func renderEntities(b *strings.Builder, m *model.Model, sourceDir, outDir string) {
	names := m.EntityNames()
	if len(names) == 0 {
		return
	}
	// Index subtypes by parent so each parent can list its kinds. names is
	// sorted, so each child list is deterministic.
	subtypes := map[string][]string{}
	for _, n := range names {
		if p := m.Entities[n].SubtypeOf; p != "" {
			subtypes[p] = append(subtypes[p], n)
		}
	}
	importTargets := importAnchors(m, sourceDir, outDir)
	b.WriteString("## Entities\n\n")
	for _, name := range names {
		ent := m.Entities[name]
		fmt.Fprintf(b, "### `%s`\n\n", name)

		if def := strings.TrimSpace(ent.Definition); def != "" {
			b.WriteString(proseBlock(def))
			b.WriteString("\n\n")
		}

		if ent.SubtypeOf != "" {
			fmt.Fprintf(b, "**Subtype of** `%s`\n\n", ent.SubtypeOf)
		}
		if kids := subtypes[name]; len(kids) > 0 {
			quoted := make([]string, len(kids))
			for i, k := range kids {
				quoted[i] = "`" + k + "`"
			}
			fmt.Fprintf(b, "**Subtypes** — %s\n\n", strings.Join(quoted, ", "))
		}

		if ent.Derived {
			d := "**Derived.** Computed on demand from other state; never persisted."
			if derivation := strings.TrimSpace(ent.Derivation); derivation != "" {
				d = fmt.Sprintf("**Derived:** %s", proseLine(derivation))
			}
			b.WriteString(d)
			b.WriteString("\n\n")
		}

		if len(ent.Relationships) > 0 {
			b.WriteString("**Relationships**\n\n")
			for _, rel := range ent.Relationships {
				parts := []string{fmt.Sprintf("`%s`", rel.Entity), rel.Cardinality}
				if rel.Symmetric {
					parts = append(parts, "symmetric")
				}
				if rel.Ownership != "" {
					parts = append(parts, rel.Ownership)
				}
				if rel.Role != "" {
					parts = append(parts, proseLine(rel.Role))
				}
				if rel.Note != "" {
					parts = append(parts, proseLine(rel.Note))
				}
				fmt.Fprintf(b, "- %s\n", strings.Join(parts, " — "))
			}
			b.WriteString("\n")
		}

		if len(ent.Attributes) > 0 {
			b.WriteString("**Attributes**\n\n")
			b.WriteString("| Name | Type | Description |\n")
			b.WriteString("| --- | --- | --- |\n")
			for _, attr := range ent.Attributes {
				desc := strings.TrimSpace(attr.Description)
				if attr.Derived {
					d := "_Derived._"
					if attr.Derivation != "" {
						d = "_Derived:_ " + attr.Derivation
					}
					if desc != "" {
						desc += " " + d
					} else {
						desc = d
					}
				}
				fmt.Fprintf(b, "| %s | %s | %s |\n", codeCell(attr.Name), typeCell(attr.Type, importTargets), mdCell(desc))
			}
			b.WriteString("\n")
		}

		renderActions(b, ent.Actions)

		if len(ent.Invariants) > 0 {
			b.WriteString("**Invariants**\n\n")
			for _, inv := range ent.Invariants {
				fmt.Fprintf(b, "- **%s** — %s\n", inv.ID, proseLine(inv.Statement))
			}
			b.WriteString("\n")
		}
	}
}

// renderActions prints actions inline when they are all bare names, and as a
// detailed list when any carries structure (actor, preserved invariants, or a
// description).
func renderActions(b *strings.Builder, actions []model.Action) {
	if len(actions) == 0 {
		return
	}
	structured := false
	for _, a := range actions {
		if a.Actor != "" || len(a.Preserves) > 0 || a.Description != "" {
			structured = true
			break
		}
	}
	if !structured {
		quoted := make([]string, len(actions))
		for i, a := range actions {
			quoted[i] = codeSpan(a.Name)
		}
		fmt.Fprintf(b, "**Actions:** %s\n\n", strings.Join(quoted, ", "))
		return
	}

	b.WriteString("**Actions**\n\n")
	for _, a := range actions {
		var detail []string
		if a.Actor != "" {
			detail = append(detail, "actor "+codeSpan(a.Actor))
		}
		if len(a.Preserves) > 0 {
			preserves := make([]string, len(a.Preserves))
			for i, id := range a.Preserves {
				preserves[i] = proseLine(id)
			}
			detail = append(detail, "preserves "+strings.Join(preserves, ", "))
		}
		line := codeSpan(a.Name)
		if len(detail) > 0 {
			line += " — " + strings.Join(detail, "; ")
		}
		if a.Description != "" {
			line += " — " + proseLine(a.Description)
		}
		fmt.Fprintf(b, "- %s\n", line)
	}
	b.WriteString("\n")
}

func renderDiagram(b *strings.Builder, m *model.Model) {
	if len(m.Entities) == 0 {
		return
	}
	b.WriteString("## Relationships\n\n")
	b.WriteString("```mermaid\n")
	b.WriteString(mermaid.ER(m))
	b.WriteString("```\n\n")
}

func renderScenarios(b *strings.Builder, m *model.Model) {
	if len(m.Scenarios) == 0 {
		return
	}

	// Resolve invariant ids to their statements for readability — across both
	// scopes, since a scenario may touch a model-level invariant.
	statement := map[string]string{}
	for _, name := range m.EntityNames() {
		for _, inv := range m.Entities[name].Invariants {
			statement[inv.ID] = inv.Statement
		}
	}
	for _, inv := range m.Invariants {
		statement[inv.ID] = inv.Statement
	}

	b.WriteString("## Scenarios\n\n")
	for _, sc := range m.Scenarios {
		fmt.Fprintf(b, "### %s\n\n", proseLine(sc.Name))

		if desc := strings.TrimSpace(sc.Description); desc != "" {
			b.WriteString(proseBlock(desc))
			b.WriteString("\n\n")
		}

		if len(sc.Actors) > 0 {
			actors := make([]string, len(sc.Actors))
			for i, a := range sc.Actors {
				actors[i] = proseLine(a)
			}
			fmt.Fprintf(b, "**Actors:** %s\n\n", strings.Join(actors, ", "))
		}

		if len(sc.Steps) > 0 {
			b.WriteString("**Steps**\n\n")
			for i, step := range sc.Steps {
				fmt.Fprintf(b, "%d. %s\n", i+1, proseLine(step))
			}
			b.WriteString("\n")
		}

		if len(sc.InvariantsTouched) > 0 {
			b.WriteString("**Invariants touched**\n\n")
			for _, id := range sc.InvariantsTouched {
				if s, ok := statement[id]; ok {
					fmt.Fprintf(b, "- **%s** — %s\n", proseLine(id), proseLine(s))
				} else {
					fmt.Fprintf(b, "- **%s**\n", proseLine(id))
				}
			}
			b.WriteString("\n")
		}
	}
}

// mdCell escapes an author-written prose value for use inside a Markdown table
// cell.
func mdCell(s string) string {
	return cellEscape(proseLine(s))
}

// codeCell renders a value as a code span inside a Markdown table cell. GFM
// recognizes a backslash-escaped pipe inside a code span, which is the only way
// a cell can carry one.
func codeCell(s string) string {
	return cellEscape(codeSpan(s))
}

func cellEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

// mdParser is a CommonMark parser used only to locate the literal regions of a
// prose string. Nothing is ever rendered through goldmark: its renderer
// normalizes and reflows text, which would rewrite prose the author wrote and
// churn every committed .md, so the escaping writes back into the original
// bytes at the offsets the parse reports (ADR-0014).
//
// The parser is built from the CommonMark defaults rather than through
// goldmark.New so the HTML renderer never enters the binary. parser.Parse is
// safe for concurrent use: its one-time setup is guarded by a sync.Once and
// each call carries its own context.
var mdParser = parser.NewParser(
	parser.WithBlockParsers(parser.DefaultBlockParsers()...),
	parser.WithInlineParsers(parser.DefaultInlineParsers()...),
	parser.WithParagraphTransformers(parser.DefaultParagraphTransformers()...),
)

// byteRange is a half-open [start, stop) region of a prose string.
type byteRange struct{ start, stop int }

// proseBlock escapes an author-written string that is emitted as its own block
// — a model, enum or scenario description, an entity definition. Fenced and
// indented code blocks are literal there, so they are left verbatim.
func proseBlock(s string) string { return escapeProse(s, true) }

// proseLine escapes an author-written string that lands inside a line — a
// heading, a list item, a table cell — collapsing it to one line first.
//
// Only code spans are literal in that position. A leading "```" or four-space
// indent cannot open a code block partway through a line, so this string,
// parsed alone, may look like a code block where the document has ordinary
// text; treating it as one would leave the HTML behind it live.
func proseLine(s string) string { return escapeProse(oneLine(s), false) }

// escapeProse escapes raw HTML in an author-written string while leaving its
// Markdown intact. A `definition:` is Markdown — models backtick their entity
// names throughout and authors use emphasis — but it is not HTML: an angle
// bracket is text the author typed, not a tag to interpret (ADR-0014).
//
// Outside a literal region, "<" and ">" become character references so they
// render as themselves. Inside one they are already literal, and escaping them
// would put a visible "&lt;" on the page, so the region is copied through
// whole.
//
// An "&" is escaped only where it introduces a character reference. Character
// references cannot produce markup — a Markdown parser decodes one to a
// character and re-escapes it on output — so this is fidelity, not safety: an
// author who wrote "&lt;" sees "&lt;", the same rule as one who wrote "<". A
// bare ampersand ("R&D", "a & b") already renders as itself and passes through
// untouched, which keeps the committed Markdown readable.
func escapeProse(s string, blockContext bool) string {
	var b strings.Builder
	i := 0
	for _, r := range literalRanges(s, blockContext) {
		escapeMarkup(&b, s[i:r.start])
		b.WriteString(s[r.start:r.stop])
		i = r.stop
	}
	escapeMarkup(&b, s[i:])
	return b.String()
}

// literalRanges returns the regions of s a CommonMark parser treats as literal
// text: the contents of code spans, and — in block context only — of fenced and
// indented code blocks. The ranges are sorted and do not overlap.
//
// The parse is what decides. A hand-rolled backtick scanner has no model of
// block structure or of backslash escapes, so it reads an escaped "\`" as a
// delimiter and lets a span run across a paragraph break — two ways to declare
// raw HTML literal that a real parser never would (#37).
//
// A code fence's info string is not returned: it is an attribute of the block
// rather than text on the page, so escaping it costs nothing and keeps an
// unclosed fence from carrying a tag on its opening line.
func literalRanges(s string, blockContext bool) []byteRange {
	src := parseSource(s)
	var out []byteRange
	appendSegments := func(segs *text.Segments) {
		for i := 0; i < segs.Len(); i++ {
			seg := segs.At(i)
			if stop := min(seg.Stop, len(s)); seg.Start < stop {
				out = append(out, byteRange{seg.Start, stop})
			}
		}
	}
	// Walk never returns an error: the callback below returns none.
	_ = ast.Walk(mdParser.Parse(text.NewReader(src)), func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		switch node := n.(type) {
		case *ast.CodeSpan:
			for c := node.FirstChild(); c != nil; c = c.NextSibling() {
				if t, ok := c.(*ast.Text); ok {
					out = append(out, byteRange{t.Segment.Start, t.Segment.Stop})
				}
			}
		case *ast.FencedCodeBlock:
			if blockContext {
				appendSegments(node.Lines())
			}
		case *ast.CodeBlock:
			if blockContext {
				appendSegments(node.Lines())
			}
		}
		return ast.WalkContinue, nil
	})

	sort.Slice(out, func(i, j int) bool { return out[i].start < out[j].start })
	merged := out[:0]
	prev := 0
	for _, r := range out {
		if r.start < prev {
			continue
		}
		merged = append(merged, r)
		prev = r.stop
	}
	return merged
}

// parseSource returns the bytes to hand the parser for s. The trailing newline
// is a workaround, not a nicety. goldmark decides whether a line is blank by
// comparing an indent measured in *columns* against the line's length in
// *bytes*, so a final line short enough for a tab to outrun it — "> \t`" — is
// called blank, and the fenced-code-block parser then indexes it at the -1 that
// marks one. That panics `modelith render` on a model that lints clean.
//
// A line ending keeps the comparison honest and costs nothing: a document is
// defined to end with one, and appending it moves no offset inside s. Upstream
// yuin/goldmark#556 fixed one path into the same -1 and v1.8.4 carries that
// fix; this input reaches it by another, and #556's own repro still panics on
// v1.8.4. TestRender_UnnormalisedProseDoesNotPanic guards it.
func parseSource(s string) []byte {
	if !strings.HasSuffix(s, "\n") {
		s += "\n"
	}
	return []byte(s)
}

func escapeMarkup(b *strings.Builder, s string) {
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case c == '<':
			b.WriteString("&lt;")
		case c == '>':
			b.WriteString("&gt;")
		case c == '&' && entityRefRE.MatchString(s[i:]):
			b.WriteString("&amp;")
		default:
			b.WriteByte(c)
		}
	}
}

// oneLine collapses a value onto a single line for use in a heading, a list
// item, or a table cell, where a stray line break would break the document
// structure. Entity names are PascalCase-constrained by the schema; titles,
// scenario names and import paths are freeform, so they get collapsed here.
// Every control character goes, not just the line breaks: the rest are
// invisible on the rendered page and belong in none of these positions.
func oneLine(s string) string {
	return strings.TrimSpace(strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, s))
}

// codeSpan renders s as a Markdown code span. The scope a bare import derives
// from its filename is arbitrary author-supplied text, and a backtick inside it
// would close the span early and let the remainder render as Markdown or raw
// HTML. CommonMark's answer is a fence one backtick longer than the longest run
// inside, which keeps the value intact instead of mangling it.
func codeSpan(s string) string {
	s = oneLine(s)
	if s == "" {
		return "` `"
	}
	fence := "`"
	for _, run := range backtickRunRE.FindAllString(s, -1) {
		if len(run) >= len(fence) {
			fence = strings.Repeat("`", len(run)+1)
		}
	}
	// CommonMark strips one leading and one trailing space from a span's
	// content, so this padding keeps a value that begins or ends with a
	// backtick from fusing with the fence.
	if strings.HasPrefix(s, "`") || strings.HasSuffix(s, "`") {
		s = " " + s + " "
	}
	return fence + s + fence
}

// linkTarget percent-encodes a path for use as a Markdown link destination.
// Escaping a value for a table cell is not escaping it for a URL: a closing
// parenthesis ends the destination early, whitespace ends it, and an angle
// bracket opens raw HTML in whatever follows. Everything outside the URL
// unreserved set and the path separator is encoded, so an ordinary relative
// path passes through unchanged and a hostile one cannot break out.
func linkTarget(p string) string {
	var b strings.Builder
	for i := 0; i < len(p); i++ {
		if c := p[i]; unreservedPathByte(c) {
			b.WriteByte(c)
		} else {
			fmt.Fprintf(&b, "%%%02X", c)
		}
	}
	return b.String()
}

func unreservedPathByte(c byte) bool {
	switch {
	case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		return true
	default:
		return strings.IndexByte("-._~/", c) >= 0
	}
}
