// Package markdown renders a domain model as a Markdown document with an
// embedded Mermaid relationships diagram. The output is meant to be committed
// next to the YAML source and read directly by people and agents.
package markdown

import (
	"fmt"
	"sort"
	"strings"

	"github.com/stacklok/modelith/internal/model"
	"github.com/stacklok/modelith/internal/render/mermaid"
)

// MDX comment syntax ({/* */}) rather than an HTML comment (<!-- -->): the docs
// are consumed by Docusaurus v3, whose MDX parser rejects HTML comments.
const generatedBanner = "{/* Generated by `modelith render`. Do not edit by hand; edit the .modelith.yaml source and re-render. */}"

// Render produces the full Markdown document for the model.
func Render(m *model.Model) string {
	var b strings.Builder

	b.WriteString(generatedBanner)
	b.WriteString("\n\n")

	title := m.Title
	if title == "" {
		title = "Domain Model"
	}
	fmt.Fprintf(&b, "# %s\n\n", oneLine(title))

	if desc := strings.TrimSpace(m.Description); desc != "" {
		b.WriteString(desc)
		b.WriteString("\n\n")
	}

	renderGlossary(&b, m)
	renderEnums(&b, m)
	renderEntities(&b, m)
	renderDiagram(&b, m)
	renderInvariants(&b, m)
	renderScenarios(&b, m)

	return b.String()
}

// renderInvariants emits the model-level invariants — cross-entity rules with no
// single owner — in a top-level section, after the relationship diagram and
// before the scenarios that exercise them. Per-entity invariants render inline
// with their entity (see renderEntities).
func renderInvariants(b *strings.Builder, m *model.Model) {
	if len(m.Invariants) == 0 {
		return
	}
	b.WriteString("## Invariants\n\n")
	for _, inv := range m.Invariants {
		fmt.Fprintf(b, "- **%s** — %s\n", inv.ID, inv.Statement)
	}
	b.WriteString("\n")
}

func renderGlossary(b *strings.Builder, m *model.Model) {
	if len(m.Glossary) == 0 {
		return
	}
	b.WriteString("## Glossary\n\n")
	terms := make([]string, 0, len(m.Glossary))
	for t := range m.Glossary {
		terms = append(terms, t)
	}
	sort.Strings(terms)
	for _, t := range terms {
		fmt.Fprintf(b, "- **`%s`** — %s\n", t, oneLine(m.Glossary[t]))
	}
	b.WriteString("\n")
}

func renderEnums(b *strings.Builder, m *model.Model) {
	if len(m.Enums) == 0 {
		return
	}
	names := make([]string, 0, len(m.Enums))
	for n := range m.Enums {
		names = append(names, n)
	}
	sort.Strings(names)

	b.WriteString("## Enums\n\n")
	for _, name := range names {
		en := m.Enums[name]
		fmt.Fprintf(b, "### `%s`\n\n", name)
		if d := strings.TrimSpace(en.Description); d != "" {
			b.WriteString(d)
			b.WriteString("\n\n")
		}
		b.WriteString("| Value | Definition |\n")
		b.WriteString("| --- | --- |\n")
		for _, v := range en.Values {
			fmt.Fprintf(b, "| `%s` | %s |\n", v.Name, mdCell(v.Definition))
		}
		b.WriteString("\n")
	}
}

func renderEntities(b *strings.Builder, m *model.Model) {
	names := m.EntityNames()
	if len(names) == 0 {
		return
	}
	b.WriteString("## Entities\n\n")
	for _, name := range names {
		ent := m.Entities[name]
		fmt.Fprintf(b, "### `%s`\n\n", name)

		if def := strings.TrimSpace(ent.Definition); def != "" {
			b.WriteString(def)
			b.WriteString("\n\n")
		}

		if len(ent.Relationships) > 0 {
			b.WriteString("**Relationships**\n\n")
			for _, rel := range ent.Relationships {
				parts := []string{fmt.Sprintf("`%s`", rel.Entity), rel.Cardinality}
				if rel.Ownership != "" {
					parts = append(parts, rel.Ownership)
				}
				if rel.Role != "" {
					parts = append(parts, rel.Role)
				}
				if rel.Note != "" {
					parts = append(parts, rel.Note)
				}
				fmt.Fprintf(b, "- %s\n", strings.Join(parts, " — "))
			}
			b.WriteString("\n")
		}

		if len(ent.Attributes) > 0 {
			b.WriteString("**Attributes**\n\n")
			b.WriteString("| Name | Type | Description |\n")
			b.WriteString("| --- | --- | --- |\n")
			for _, attr := range ent.Attributes {
				desc := strings.TrimSpace(attr.Description)
				if attr.Derived {
					d := "_Derived._"
					if attr.Derivation != "" {
						d = "_Derived:_ " + attr.Derivation
					}
					if desc != "" {
						desc += " " + d
					} else {
						desc = d
					}
				}
				fmt.Fprintf(b, "| `%s` | %s | %s |\n", attr.Name, mdCell(attr.Type), mdCell(desc))
			}
			b.WriteString("\n")
		}

		renderActions(b, ent.Actions)

		if len(ent.Invariants) > 0 {
			b.WriteString("**Invariants**\n\n")
			for _, inv := range ent.Invariants {
				fmt.Fprintf(b, "- **%s** — %s\n", inv.ID, inv.Statement)
			}
			b.WriteString("\n")
		}
	}
}

// renderActions prints actions inline when they are all bare names, and as a
// detailed list when any carries structure (actor, preserved invariants, or a
// description).
func renderActions(b *strings.Builder, actions []model.Action) {
	if len(actions) == 0 {
		return
	}
	structured := false
	for _, a := range actions {
		if a.Actor != "" || len(a.Preserves) > 0 || a.Description != "" {
			structured = true
			break
		}
	}
	if !structured {
		quoted := make([]string, len(actions))
		for i, a := range actions {
			quoted[i] = "`" + a.Name + "`"
		}
		fmt.Fprintf(b, "**Actions:** %s\n\n", strings.Join(quoted, ", "))
		return
	}

	b.WriteString("**Actions**\n\n")
	for _, a := range actions {
		var detail []string
		if a.Actor != "" {
			detail = append(detail, fmt.Sprintf("actor `%s`", a.Actor))
		}
		if len(a.Preserves) > 0 {
			detail = append(detail, "preserves "+strings.Join(a.Preserves, ", "))
		}
		line := "`" + a.Name + "`"
		if len(detail) > 0 {
			line += " — " + strings.Join(detail, "; ")
		}
		if a.Description != "" {
			line += " — " + oneLine(a.Description)
		}
		fmt.Fprintf(b, "- %s\n", line)
	}
	b.WriteString("\n")
}

func renderDiagram(b *strings.Builder, m *model.Model) {
	if len(m.Entities) == 0 {
		return
	}
	b.WriteString("## Relationships\n\n")
	b.WriteString("```mermaid\n")
	b.WriteString(mermaid.ER(m))
	b.WriteString("```\n\n")
}

func renderScenarios(b *strings.Builder, m *model.Model) {
	if len(m.Scenarios) == 0 {
		return
	}

	// Resolve invariant ids to their statements for readability — across both
	// scopes, since a scenario may touch a model-level invariant.
	statement := map[string]string{}
	for _, name := range m.EntityNames() {
		for _, inv := range m.Entities[name].Invariants {
			statement[inv.ID] = inv.Statement
		}
	}
	for _, inv := range m.Invariants {
		statement[inv.ID] = inv.Statement
	}

	b.WriteString("## Scenarios\n\n")
	for _, sc := range m.Scenarios {
		fmt.Fprintf(b, "### %s\n\n", oneLine(sc.Name))

		if desc := strings.TrimSpace(sc.Description); desc != "" {
			b.WriteString(desc)
			b.WriteString("\n\n")
		}

		if len(sc.Actors) > 0 {
			fmt.Fprintf(b, "**Actors:** %s\n\n", strings.Join(sc.Actors, ", "))
		}

		if len(sc.Steps) > 0 {
			b.WriteString("**Steps**\n\n")
			for i, step := range sc.Steps {
				fmt.Fprintf(b, "%d. %s\n", i+1, step)
			}
			b.WriteString("\n")
		}

		if len(sc.InvariantsTouched) > 0 {
			b.WriteString("**Invariants touched**\n\n")
			for _, id := range sc.InvariantsTouched {
				if s, ok := statement[id]; ok {
					fmt.Fprintf(b, "- **%s** — %s\n", id, s)
				} else {
					fmt.Fprintf(b, "- **%s**\n", id)
				}
			}
			b.WriteString("\n")
		}
	}
}

// mdCell escapes a value for use inside a Markdown table cell.
func mdCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

// oneLine collapses a value onto a single line for use in a heading, where a
// stray newline would break the document structure. Entity names are
// PascalCase-constrained by the schema; titles and scenario names are freeform,
// so they get collapsed here.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.TrimSpace(s)
}
